### PR TITLE
[feat] use prev name as default name when rename

### PR DESCRIPTION
**Pull request by LintaoAmons**
makes it easier to change the name

### CODE REVIEW

**Comment by X3eRo0** [comment]
Thanks for your contribution, I love it <3.
can you fix the indentation? and I can see there are some tabs. Once you fix it I will merge.

**Comment by LintaoAmons** [comment]
Hi~
I updated the format
LOL, my local lua indentation is 2, so I  added the whitespace manually

**Comment by X3eRo0** [comment]
Thanks

**Comment by LintaoAmons** [comment]
Thanks for making this wonderful plugin, always want to find something like ranger/lf in neovim.

**Pull request merged**
